version: '3.8'

services:
  gcsb_ecommerce:
    environment:
      DBCONN: "Server=gcsb_ecommerce_db;Port=5432;Database=postgres;User Id=postgres;Password=postgres"
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - gcsb_ecommerce_db
      - gcsb_ecommerce_rabbitmq
    networks:
      - gcsbEcommerce
  gcsb_ecommerce_db:
    image: postgres:14.3
    restart: unless-stopped
    ports:
      - 5544:5432
    networks:
      - gcsbEcommerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  gcsb_ecommerce_rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5674:5672"
      - "15673:15672"
    networks:
      - gcsbEcommerce
      
networks:
  gcsbEcommerce:
    driver: bridge
volumes:
  postgres-data:
